### ISSUE TITLE
Diskussion: Weshalb nicht (fast) alles auf Jsonlist2 via Telnet?

### ISSUE THREAD

**Issue by rretsiem** [winne27/fhem.js#2]
Gibt es einen Grund warum man das normale "list" noch benötigt wenn man doch ein bereits fertiges JSON via Jsonlist2 vom FHEM.pl erhält?
Damit würde doch das getAllValues() und auch das füllen des buffer Objektes doch deutlich leichter und ohne viel Aufwand möglich sein. Zusätzlich gewinnt man dadurch das man auch im Buffer alle Readings hat und nicht nur den State.

Daher mal als Diskussion hier.

**Comment by winne27** [comment]
Mit inform on bekommt man Statusänderungen mitgeteilt und kann diese Information direkt mit emit an die Clients weiterleiten. Soll ein Jsonlist2 bei einer Statusänderung geschickt werden, muss nach dem Empfang der Statusänderung erst ein Jsonlist2-Request für die Device an den fhem-Server geschickt werden und auf die Antwort gewartet werden, bevor die Änderung als Jsonlist2 an dieClients geschickt werden kann. Damit wird die Meldung einige Sekunden verzögert, da Jsonlist2 Abfragen sehr lange dauern, zumindest bei meiner Umgebung (Banana Pi)
